version: "3.8"
services:
  pg-reward-system:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rewardsystem
      POSTGRES_DB: reward-system
    volumes:
      - reward-system-vol:/var/lib/postgresql/data
    ports:
      # - ../ui/server/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - 5433:5432

volumes:
  reward-system-vol:
