version: "3"
services:
  pg-reward-system:
    image: postgres:16-alpine
    ports:
      - 5433:5432
    volumes:
      - reward-system-vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rewardsystem
      - POSTGRES_DB=reward-system

volumes:
  reward-system-vol:
