import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";

import "./globals.css";
import { AuthProvider } from "../contexts";
import AppProvider from "../contexts/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Welcome to my website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <AppProvider>
          <body className={inter.className}>{children}</body>

          <ToastContainer position="top-center" autoClose={2000} className="capitalize" />
        </AppProvider>
      </AuthProvider>
    </html>
  );
}
